name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '23'
      - name: Install dependencies
        run: npm ci --prefix frontend
      - name: Setup AWS Credentials
        run: |
          aws configure set region "us-east-1"
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Download assets
        run: ./download_assets.sh
      - name: Build frontend
        run: ./build.sh
      - name: Deploy frontend
        run: ./deploy.sh
